# Generated by Django 4.1.13 on 2024-12-13 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'verbose_name': '系统日志', 'verbose_name_plural': '系统日志'},
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='path',
        ),
        migrations.AddField(
            model_name='systemlog',
            name='action',
            field=models.CharField(default='系统操作', max_length=200, verbose_name='操作行为'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='content',
            field=models.TextField(blank=True, verbose_name='详细内容'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='execution_time',
            field=models.FloatField(blank=True, null=True, verbose_name='执行时间(ms)'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='request_body',
            field=models.TextField(blank=True, verbose_name='请求内容'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='请求路径'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='response_body',
            field=models.TextField(blank=True, verbose_name='响应内容'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='response_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='响应代码'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '处理中')], db_index=True, default='success', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='type',
            field=models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('email', '邮件操作'), ('template', '模板操作'), ('schedule', '定时任务'), ('system', '系统操作'), ('api', 'API调用'), ('error', '系统错误')], db_index=True, default='system', max_length=20, verbose_name='日志类型'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='level',
            field=models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], db_index=True, default='info', max_length=10, verbose_name='日志级别'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'type', 'level', 'created_at'], name='logs_system_user_id_00230e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['status', 'created_at'], name='logs_system_status_af3c06_idx'),
        ),
    ]
