# Generated by Django 4.1.13 on 2024-12-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0002_emailschedule_emailhistory_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='email_images/%Y/%m/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '邮件图片',
                'verbose_name_plural': '邮件图片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('notice', '通知'), ('marketing', '营销'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'ordering': ['-updated_at'],
            },
        ),
    ]
