# Generated by Django 4.1.13 on 2024-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0004_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('notice', '通知'), ('marketing', '营销'), ('other', '其他')], default='other', max_length=20, verbose_name='分类'),
        ),
    ]
