# Generated by Django 4.1.13 on 2024-12-13 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_service', '0005_emailtemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
    ]
